"""Executable fixed-gain plan bank for the candidate-only meta-control study.

The Qwen-visible decision is a plan name.  Continuous actions are always
generated by the unchanged Learned-H1 forward ensemble plus the CEM search in
this module.  Every plan shares action bounds, population, iterations, horizon,
maximum control steps, and strict termination tolerance.  The only permitted
plan differences are measurement source, metric objective schedule, active
actuator schedule, and observation-triggered phase transition.
"""

from __future__ import annotations

import hashlib
import json
import math
from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from typing import Any

import numpy as np
from scipy.ndimage import maximum_filter

from continuous_control_v12.contracts import (
    ACTION_FIELDS,
    Bounds,
    action_dict,
    apply_action,
    metrics_dict,
    metrics_vector,
    position_dict,
    position_vector,
    tolerance_vector,
)
from continuous_control_v12.simulator import simulate_state
from vlm_optics_benchmark.reflection_width_relative import (
    inject_width_relative_reflection,
)
from vlm_optics_benchmark.visual_anomalies import moment_metrics

from .protocol import PLAN_NAMES


ALL_DOFS = ("lens_x", "lens_y", "camera_x", "camera_y")
PLAN_BANK_REVISION = "revision1_mandatory_specialist_first_step"
FIXED_CONTROLLER_CONFIG: dict[str, Any] = {
    "horizon": 1,
    "population": 24,
    "elites": 6,
    "cem_iterations": 3,
    "max_control_steps": 4,
    "mean_error_weight": 0.15,
    "movement_weight": 0.02,
    "limit_penalty": 10.0,
    "boundary_penalty": 1.0,
    "uncertainty_weight": 0.1,
    "strict_success_threshold": 1.0,
    "phase_one_max_steps": 2,
}


def canonical_hash(value: Any) -> str:
    payload = json.dumps(
        value, sort_keys=True, separators=(",", ":"), allow_nan=False
    ).encode("utf-8")
    return hashlib.sha256(payload).hexdigest()


@dataclass(frozen=True)
class PlanSpec:
    name: str
    measurement_source: str
    phase_one_metric_weights: tuple[float, float, float, float, float]
    phase_one_transition: str
    actuator_policy: str

    def to_dict(self) -> dict[str, Any]:
        return {
            "name": self.name,
            "measurement_source": self.measurement_source,
            "phase_one_metric_weights": list(self.phase_one_metric_weights),
            "phase_one_transition": self.phase_one_transition,
            "actuator_policy": self.actuator_policy,
        }


def build_plan_bank() -> dict[str, PlanSpec]:
    plans = {
        "direct_all_five": PlanSpec(
            "direct_all_five",
            "standard",
            (1.0, 1.0, 1.0, 1.0, 1.0),
            "none_direct_replan_to_end",
            "all_actuators",
        ),
        "centroid_then_full": PlanSpec(
            "centroid_then_full",
            "standard",
            (1.0, 1.0, 0.05, 0.05, 0.05),
            "mandatory_first_step_then_centroid_xy_tolerance_or_two_step_budget",
            "all_actuators",
        ),
        "shape_then_full": PlanSpec(
            "shape_then_full",
            "standard",
            (0.05, 0.05, 1.0, 1.0, 1.0),
            "mandatory_first_step_then_width_xy_intensity_tolerance_or_two_step_budget",
            "all_actuators",
        ),
        "primary_spot_then_full": PlanSpec(
            "primary_spot_then_full",
            "primary_spot",
            (1.0, 1.0, 0.20, 0.20, 0.20),
            "mandatory_primary_spot_centroid_first_step_then_all_five",
            "all_actuators",
        ),
        "boundary_safe_then_full": PlanSpec(
            "boundary_safe_then_full",
            "standard",
            (1.0, 1.0, 1.0, 1.0, 1.0),
            "one_safe_subset_step_then_restore_all_actuators",
            "probe_and_legal_boundary_safe_subset",
        ),
    }
    if tuple(plans) != PLAN_NAMES:
        raise RuntimeError("plan registry order changed")
    return plans


def _moments_to_lab(capture: Mapping[str, Any], image_moments: np.ndarray) -> np.ndarray:
    clean_image = moment_metrics(np.asarray(capture["intensity"], dtype=np.float64))
    clean_lab = metrics_vector(capture["metrics"])
    output = clean_lab.copy()
    output[:4] += np.asarray(image_moments[:4]) - clean_image[:4]
    output[4] = float(image_moments[4])
    return output


def apply_sensor_family(
    clean_image: np.ndarray,
    family: str,
    anomaly: Mapping[str, Any],
) -> tuple[np.ndarray, dict[str, Any]]:
    """Create the actual sensor image used by the measurement specialist."""

    values = np.clip(np.asarray(clean_image, dtype=np.float64), 0.0, None)
    if family == "nominal":
        return values.astype(np.float32), {"family": family, "operation": "identity"}
    if family == "sensor_saturation":
        level = float(anomaly["clip_level_fraction_of_peak"]) * max(
            float(values.max()), 1e-30
        )
        image = np.minimum(values, level)
        return image.astype(np.float32), {
            "family": family,
            "operation": "hard_sensor_clip",
            "clip_level_absolute": level,
            "clip_level_fraction_of_peak": float(
                anomaly["clip_level_fraction_of_peak"]
            ),
        }
    if family == "width_relative_reflection":
        image, metadata = inject_width_relative_reflection(
            values,
            k=float(anomaly["k"]),
            amplitude=float(anomaly["amplitude"]),
            width_ratio=float(anomaly["width_ratio"]),
            angle_radians=float(anomaly["angle_radians"]),
            normalize_peak=False,
        )
        return image, {"family": family, **metadata}
    raise ValueError(f"unknown sensor family: {family}")


def _weighted_gaussian_em(image: np.ndarray) -> tuple[np.ndarray, dict[str, Any]]:
    """Deblend the brighter primary spot from a two-component intensity image.

    This specialist uses only the observed image.  It never receives the clean
    image, anomaly label, injection parameters, or simulator setup context.
    """

    values = np.clip(np.asarray(image, dtype=np.float64), 0.0, None)
    peak = float(values.max())
    if not np.isfinite(peak) or peak <= 0.0:
        raise ValueError("primary-spot measurement requires a positive finite image")
    base = moment_metrics(values)
    sigma_guess = max(float(np.mean(base[2:4])), 1.0)
    filter_size = max(3, int(round(sigma_guess * 0.65)) * 2 + 1)
    local = values == maximum_filter(values, size=filter_size, mode="constant")
    candidates = np.argwhere(local & (values >= 0.08 * peak))
    candidates = sorted(
        candidates.tolist(), key=lambda yx: float(values[tuple(yx)]), reverse=True
    )
    primary_yx = np.asarray(candidates[0] if candidates else np.unravel_index(np.argmax(values), values.shape), dtype=np.float64)
    secondary_yx = None
    for candidate in candidates[1:]:
        point = np.asarray(candidate, dtype=np.float64)
        if float(np.linalg.norm(point - primary_yx)) >= max(1.25 * sigma_guess, 3.0):
            secondary_yx = point
            break
    if secondary_yx is None:
        # Overlapping Gaussians need not form two local maxima.  A reflection
        # still displaces the full-image centroid away from the brightest peak;
        # use that observed asymmetry to initialize the second EM component.
        full_centroid_yx = np.asarray([base[1], base[0]], dtype=np.float64)
        displacement = full_centroid_yx - primary_yx
        if float(np.linalg.norm(displacement)) >= max(0.20 * sigma_guess, 1.0):
            inferred = primary_yx + displacement / 0.30
            inferred[0] = np.clip(inferred[0], 0.0, values.shape[0] - 1.0)
            inferred[1] = np.clip(inferred[1], 0.0, values.shape[1] - 1.0)
            if float(np.linalg.norm(inferred - primary_yx)) >= max(
                1.25 * sigma_guess, 3.0
            ):
                secondary_yx = inferred
    if secondary_yx is None:
        return base, {
            "method": "primary_spot_image_specialist_v1",
            "components": 1,
            "secondary_peak_detected": False,
            "source": "observed_image_only",
        }

    threshold = peak * 1e-5
    y, x = np.nonzero(values >= threshold)
    weights = values[y, x]
    coordinates = np.stack([x.astype(np.float64), y.astype(np.float64)], axis=1)
    if len(coordinates) > 120_000:
        stride = int(math.ceil(len(coordinates) / 120_000))
        coordinates = coordinates[::stride]
        weights = weights[::stride] * stride
    means = np.asarray(
        [[primary_yx[1], primary_yx[0]], [secondary_yx[1], secondary_yx[0]]],
        dtype=np.float64,
    )
    variance = max(sigma_guess**2, 1.0)
    covariances = np.asarray([np.eye(2) * variance, np.eye(2) * variance])
    mixing = np.asarray([0.70, 0.30], dtype=np.float64)
    for _ in range(18):
        likelihoods = []
        for component in range(2):
            covariance = covariances[component] + np.eye(2) * 1e-4
            inverse = np.linalg.inv(covariance)
            delta = coordinates - means[component]
            exponent = np.einsum("ni,ij,nj->n", delta, inverse, delta)
            normalizer = 2.0 * math.pi * math.sqrt(max(np.linalg.det(covariance), 1e-12))
            likelihoods.append(mixing[component] * np.exp(-0.5 * exponent) / normalizer)
        likelihood = np.stack(likelihoods, axis=1)
        responsibilities = likelihood / np.maximum(likelihood.sum(axis=1, keepdims=True), 1e-300)
        weighted_responsibility = responsibilities * weights[:, None]
        masses = np.maximum(weighted_responsibility.sum(axis=0), 1e-12)
        mixing = masses / masses.sum()
        means = (weighted_responsibility.T @ coordinates) / masses[:, None]
        for component in range(2):
            delta = coordinates - means[component]
            covariance = (
                (delta * weighted_responsibility[:, component, None]).T @ delta
            ) / masses[component]
            eigenvalues, eigenvectors = np.linalg.eigh(covariance)
            eigenvalues = np.clip(eigenvalues, 0.25, (4.0 * sigma_guess) ** 2)
            covariances[component] = (
                eigenvectors @ np.diag(eigenvalues) @ eigenvectors.T
            )
    peak_scores = np.asarray(
        [
            mixing[index]
            / (2.0 * math.pi * math.sqrt(max(np.linalg.det(covariances[index]), 1e-12)))
            for index in range(2)
        ]
    )
    primary = int(np.argmax(peak_scores))
    total_power = float(values.sum())
    amplitude = total_power * float(mixing[primary]) / (
        2.0 * math.pi * math.sqrt(max(np.linalg.det(covariances[primary]), 1e-12))
    )
    result = np.asarray(
        [
            means[primary, 0],
            means[primary, 1],
            math.sqrt(max(covariances[primary, 0, 0], 1e-12)),
            math.sqrt(max(covariances[primary, 1, 1], 1e-12)),
            amplitude,
        ],
        dtype=np.float64,
    )
    return result, {
        "method": "primary_spot_image_specialist_v1",
        "components": 2,
        "secondary_peak_detected": True,
        "source": "observed_image_only",
        "component_mixing": mixing.tolist(),
        "component_means_xy": means.tolist(),
        "selected_primary_component": primary,
    }


def measure_capture(
    capture: Mapping[str, Any],
    *,
    family: str,
    anomaly: Mapping[str, Any],
    source: str,
) -> tuple[np.ndarray, np.ndarray, dict[str, Any]]:
    sensor_image, sensor_metadata = apply_sensor_family(
        np.asarray(capture["intensity"]), family, anomaly
    )
    if source == "standard":
        image_moments = moment_metrics(sensor_image)
        specialist = {
            "method": "standard_full_image_moments",
            "source": "observed_image_only",
        }
    elif source == "primary_spot":
        image_moments, specialist = _weighted_gaussian_em(sensor_image)
    else:
        raise ValueError(f"unknown measurement source: {source}")
    measured = _moments_to_lab(capture, image_moments)
    if measured.shape != (5,) or not np.isfinite(measured).all():
        raise ValueError("measurement specialist returned invalid five-metric state")
    return measured, sensor_image, {
        "measurement_source": source,
        "sensor": sensor_metadata,
        "specialist": specialist,
        "image_moments": image_moments.tolist(),
    }


def _active_mask(active_dofs: Sequence[str]) -> np.ndarray:
    unknown = set(active_dofs) - set(ALL_DOFS)
    if unknown or not active_dofs:
        raise ValueError(f"invalid active actuator set: {active_dofs}")
    return np.asarray([name in set(active_dofs) for name in ALL_DOFS], dtype=bool)


class PlanCEM:
    """Vectorized horizon-one CEM with executable metric and actuator policies."""

    def __init__(
        self,
        *,
        model: Any,
        setup_context: Mapping[str, Any],
        bounds: Bounds,
        config: Mapping[str, Any],
        seed: int,
    ) -> None:
        supplied = dict(config)
        if supplied != FIXED_CONTROLLER_CONFIG:
            raise ValueError("controller config differs from the locked fixed-gain profile")
        if int(supplied["horizon"]) != 1:
            raise ValueError("candidate plan bank is Learned-H1 only")
        bounds.validate()
        self.model = model
        self.setup_context = dict(setup_context)
        self.bounds = bounds
        self.config = supplied
        self.seed = int(seed)
        self.rng = np.random.default_rng(self.seed)

    def _predict(self, positions: np.ndarray, metrics: np.ndarray, actions: np.ndarray) -> dict[str, Any]:
        return self.model.predict(
            self.setup_context,
            positions,
            metrics,
            actions,
        )

    def probe_actuators(
        self, positions: np.ndarray, metrics: np.ndarray
    ) -> dict[str, Any]:
        actions = []
        for axis in range(4):
            for sign in (-1.0, 1.0):
                action = np.zeros(4, dtype=np.float64)
                action[axis] = sign * 0.5 * self.bounds.action_high[axis]
                feasible = np.minimum(
                    np.maximum(action, self.bounds.position_low - positions),
                    self.bounds.position_high - positions,
                )
                actions.append(feasible)
        action_array = np.asarray(actions)
        predicted = self._predict(positions, metrics, action_array)
        next_metrics = np.asarray(predicted["predicted_next_metrics"], dtype=np.float64)
        normalized_delta = np.abs(next_metrics - metrics[None, :]) / tolerance_vector(metrics)[None, :]
        uncertainty = np.asarray(predicted["uncertainty"], dtype=np.float64)
        rows = []
        sensitivity = []
        for axis, name in enumerate(ALL_DOFS):
            pair = normalized_delta[2 * axis : 2 * axis + 2]
            score = float(np.max(pair))
            sensitivity.append(score)
            rows.append(
                {
                    "actuator": name,
                    "actions_mm": action_array[2 * axis : 2 * axis + 2].tolist(),
                    "normalized_metric_delta": pair.tolist(),
                    "mean_uncertainty": float(
                        uncertainty[2 * axis : 2 * axis + 2].mean()
                    ),
                    "sensitivity": score,
                }
            )
        lower_margin = positions - self.bounds.position_low
        upper_margin = self.bounds.position_high - positions
        dangerous = np.minimum(lower_margin, upper_margin) <= self.bounds.action_high + 1e-12
        threshold = float(np.quantile(np.asarray(sensitivity), 0.25))
        safe = [
            name
            for index, name in enumerate(ALL_DOFS)
            if not dangerous[index] and sensitivity[index] + 1e-12 >= threshold
        ]
        if len(safe) == 4:
            safe.remove(ALL_DOFS[int(np.argmin(sensitivity))])
        if not safe:
            safe = [ALL_DOFS[int(np.argmax(sensitivity))]]
        return {
            "rows": rows,
            "sensitivity": dict(zip(ALL_DOFS, sensitivity, strict=True)),
            "lower_position_margin_mm": lower_margin.tolist(),
            "upper_position_margin_mm": upper_margin.tolist(),
            "dangerous_by_legal_boundary": dict(zip(ALL_DOFS, dangerous.tolist(), strict=True)),
            "ineffective_threshold": threshold,
            "safe_subset": safe,
        }

    def plan(
        self,
        *,
        positions: np.ndarray,
        current_metrics: np.ndarray,
        target_metrics: np.ndarray,
        tolerance_reference: np.ndarray,
        metric_weights: Sequence[float],
        active_dofs: Sequence[str],
    ) -> dict[str, Any]:
        positions = position_vector(positions)
        current = metrics_vector(current_metrics)
        target = metrics_vector(target_metrics)
        reference = metrics_vector(tolerance_reference)
        weights = np.asarray(metric_weights, dtype=np.float64)
        if weights.shape != (5,) or np.any(weights < 0.0) or not np.any(weights > 0.0):
            raise ValueError("metric weights must be a nonnegative active five-vector")
        mask = _active_mask(active_dofs)
        population = int(self.config["population"])
        elites = int(self.config["elites"])
        iterations = int(self.config["cem_iterations"])
        mean = np.zeros(4, dtype=np.float64)
        std = self.bounds.action_high * 0.75
        mean[~mask] = 0.0
        std[~mask] = 0.0
        best: dict[str, Any] | None = None
        history = []
        for iteration in range(iterations):
            requested = self.rng.normal(mean, std, size=(population, 4))
            requested[:, ~mask] = 0.0
            requested[0] = 0.0
            injected = 1
            for axis in range(4):
                if not mask[axis]:
                    continue
                for sign in (-1.0, 1.0):
                    if injected >= population:
                        break
                    requested[injected] = 0.0
                    requested[injected, axis] = sign * self.bounds.action_high[axis]
                    injected += 1
            bounded = np.clip(requested, self.bounds.action_low, self.bounds.action_high)
            effective = np.minimum(bounded, self.bounds.position_high - positions)
            effective = np.maximum(effective, self.bounds.position_low - positions)
            effective[:, ~mask] = 0.0
            # Match the frozen H1 CEM contract: clipping a Gaussian proposal to
            # the legal per-step action box is normal sampling behavior.  The
            # limit penalty applies only when the already action-bounded value
            # must be projected again by the absolute actuator-position box.
            projected = np.any(np.abs(effective - bounded) > 1e-12, axis=1)
            prediction = self._predict(positions, current, effective)
            terminal = np.asarray(prediction["predicted_next_metrics"], dtype=np.float64)
            uncertainty = np.asarray(prediction["uncertainty"], dtype=np.float64)
            auxiliary = prediction["auxiliary_predictions"]
            normalized = np.abs(terminal - target[None, :]) / tolerance_vector(reference)[None, :]
            weighted = normalized * weights[None, :]
            terminal_max = weighted.max(axis=1)
            terminal_mean = weighted.sum(axis=1) / float(weights.sum())
            movement = np.abs(effective / self.bounds.action_high[None, :]).sum(axis=1)
            boundary_cost = np.asarray(auxiliary["clipping_fraction"], dtype=np.float64)
            boundary_cost += np.asarray(auxiliary["camera_boundary_probability"], dtype=np.float64)
            uncertainty_cost = uncertainty.mean(axis=1)
            scores = (
                1.10 * terminal_max
                + float(self.config["mean_error_weight"]) * terminal_mean
                + float(self.config["movement_weight"]) * movement
                + float(self.config["boundary_penalty"]) * boundary_cost
                + float(self.config["uncertainty_weight"]) * uncertainty_cost
                + float(self.config["limit_penalty"]) * projected.astype(np.float64)
            )
            order = np.argsort(scores, kind="stable")
            elite_indices = order[:elites]
            elite = effective[elite_indices]
            mean = elite.mean(axis=0)
            std = np.maximum(elite.std(axis=0), self.bounds.action_high * 0.03)
            mean[~mask] = 0.0
            std[~mask] = 0.0
            index = int(order[0])
            candidate = {
                "score": float(scores[index]),
                "requested_action": bounded[index].copy(),
                "action": effective[index].copy(),
                "predicted_next_metrics": terminal[index].copy(),
                "uncertainty": uncertainty[index].copy(),
                "normalized_error": normalized[index].copy(),
                "weighted_normalized_error": weighted[index].copy(),
                "limit_projected": bool(projected[index]),
                "iteration": iteration + 1,
            }
            if best is None or candidate["score"] < best["score"]:
                best = candidate
            history.append(
                {
                    "iteration": iteration + 1,
                    "best_score": float(scores[index]),
                    "elite_score_mean": float(scores[elite_indices].mean()),
                    "unique_effective_action_fraction": float(
                        len(np.unique(effective, axis=0)) / population
                    ),
                    "active_dofs": list(active_dofs),
                    "metric_weights": weights.tolist(),
                }
            )
        assert best is not None
        return {
            "selected_action": action_dict(best["action"]),
            "selected_requested_action": action_dict(best["requested_action"]),
            "predicted_next_metrics": metrics_dict(best["predicted_next_metrics"]),
            "uncertainty": best["uncertainty"].tolist(),
            "normalized_error": best["normalized_error"].tolist(),
            "weighted_normalized_error": best["weighted_normalized_error"].tolist(),
            "score": best["score"],
            "selected_iteration": best["iteration"],
            "limit_projected": best["limit_projected"],
            "metric_weights": weights.tolist(),
            "active_dofs": list(active_dofs),
            "candidate_sequences_evaluated": population * iterations,
            "iteration_history": history,
        }


def strict_components(metrics: np.ndarray, target: np.ndarray, reference: np.ndarray) -> np.ndarray:
    return np.abs(metrics_vector(metrics) - metrics_vector(target)) / tolerance_vector(reference)


def _phase_policy(
    spec: PlanSpec,
    *,
    step: int,
    measured: np.ndarray,
    target: np.ndarray,
    reference: np.ndarray,
    safe_subset: Sequence[str],
) -> tuple[str, tuple[float, ...], tuple[str, ...], bool]:
    components = strict_components(measured, target, reference)
    full = (1.0, 1.0, 1.0, 1.0, 1.0)
    if spec.name == "centroid_then_full":
        phase_one = step == 0 or (
            step < int(FIXED_CONTROLLER_CONFIG["phase_one_max_steps"])
            and float(components[:2].max()) > 1.0
        )
        return (
            "centroid_phase" if phase_one else "all_five_phase",
            spec.phase_one_metric_weights if phase_one else full,
            ALL_DOFS,
            not phase_one,
        )
    if spec.name == "shape_then_full":
        phase_one = step == 0 or (
            step < int(FIXED_CONTROLLER_CONFIG["phase_one_max_steps"])
            and float(components[2:].max()) > 1.0
        )
        return (
            "shape_phase" if phase_one else "all_five_phase",
            spec.phase_one_metric_weights if phase_one else full,
            ALL_DOFS,
            not phase_one,
        )
    if spec.name == "boundary_safe_then_full":
        phase_one = step == 0
        return (
            "boundary_safe_phase" if phase_one else "all_actuator_all_five_phase",
            full,
            tuple(safe_subset) if phase_one else ALL_DOFS,
            not phase_one,
        )
    if spec.name == "primary_spot_then_full":
        phase_one = step == 0
        return (
            "primary_spot_centroid_phase" if phase_one else "primary_spot_all_five_phase",
            spec.phase_one_metric_weights if phase_one else full,
            ALL_DOFS,
            not phase_one,
        )
    return "direct_all_five_phase", full, ALL_DOFS, True


class FixedGainPlanController:
    """Execute one plan with real measurement, phase, actuator, and CEM effects."""

    def __init__(
        self,
        *,
        model: Any,
        base_config_path: str,
        fixed_config: Mapping[str, Any] | None = None,
    ) -> None:
        self.model = model
        self.base_config_path = str(base_config_path)
        self.fixed_config = dict(fixed_config or FIXED_CONTROLLER_CONFIG)
        if self.fixed_config != FIXED_CONTROLLER_CONFIG:
            raise ValueError("fixed controller profile may not be changed per plan")
        self.plan_bank = build_plan_bank()

    def run_episode(
        self,
        group: Mapping[str, Any],
        *,
        plan_name: str,
        cem_seed: int,
        initial_capture: Mapping[str, Any] | None = None,
    ) -> dict[str, Any]:
        if plan_name not in self.plan_bank:
            raise ValueError(f"unknown plan: {plan_name}")
        spec = self.plan_bank[plan_name]
        bounds = Bounds(
            action_low=np.asarray(group["bounds"]["action_low"], dtype=np.float64),
            action_high=np.asarray(group["bounds"]["action_high"], dtype=np.float64),
            position_low=np.asarray(group["bounds"]["position_low"], dtype=np.float64),
            position_high=np.asarray(group["bounds"]["position_high"], dtype=np.float64),
        )
        planner = PlanCEM(
            model=self.model,
            setup_context=group["setup_context"],
            bounds=bounds,
            config=self.fixed_config,
            seed=cem_seed,
        )
        position = position_vector(group["initial_positions_mm"])
        target = metrics_vector(group["target_metrics"])
        reference = metrics_vector(group["tolerance_reference_metrics"])
        capture = initial_capture
        if capture is None:
            capture = simulate_state(
                group["setup_context"],
                position_dict(position),
                group["simulator_fixed"],
                self.base_config_path,
                bounds,
            )
        clean = metrics_vector(capture["metrics"])
        initial_clean = clean.copy()
        measured, sensor_image, measurement_evidence = measure_capture(
            capture,
            family=str(group["visual_family"]),
            anomaly=group.get("anomaly", {}),
            source=spec.measurement_source,
        )
        probe_audit = planner.probe_actuators(position, measured)
        safe_subset = tuple(probe_audit["safe_subset"])
        trace = []
        phase_transitions = []
        previous_phase = None
        boundary_risk_cost = 0.0
        violation_count = 0
        termination_reason = "max_control_steps"
        for step in range(int(self.fixed_config["max_control_steps"])):
            observed_components = strict_components(measured, target, reference)
            if float(observed_components.max()) <= float(self.fixed_config["strict_success_threshold"]):
                termination_reason = "observed_strict_all_five_success"
                break
            phase, metric_weights, active_dofs, phase_one_complete = _phase_policy(
                spec,
                step=step,
                measured=measured,
                target=target,
                reference=reference,
                safe_subset=safe_subset,
            )
            if phase != previous_phase:
                phase_transitions.append(
                    {
                        "at_control_step": step,
                        "from": previous_phase,
                        "to": phase,
                        "triggered_by_observation": True,
                        "observed_normalized_components": observed_components.tolist(),
                    }
                )
                previous_phase = phase
            planned = planner.plan(
                positions=position,
                current_metrics=measured,
                target_metrics=target,
                tolerance_reference=reference,
                metric_weights=metric_weights,
                active_dofs=active_dofs,
            )
            action = np.asarray(
                [planned["selected_action"][field] for field in ACTION_FIELDS],
                dtype=np.float64,
            )
            before = position.copy()
            next_position = apply_action(position, action, bounds, project=False)
            lower_margin = next_position - bounds.position_low
            upper_margin = bounds.position_high - next_position
            normalized_margin = np.minimum(lower_margin, upper_margin) / np.maximum(
                bounds.action_high, 1e-12
            )
            boundary_risk_cost += float(np.maximum(1.0 - normalized_margin, 0.0).sum())
            if np.any(next_position < bounds.position_low - 1e-12) or np.any(
                next_position > bounds.position_high + 1e-12
            ):
                violation_count += 1
            next_capture = simulate_state(
                group["setup_context"],
                position_dict(next_position),
                group["simulator_fixed"],
                self.base_config_path,
                bounds,
            )
            next_clean = metrics_vector(next_capture["metrics"])
            next_measured, next_sensor_image, next_measurement_evidence = measure_capture(
                next_capture,
                family=str(group["visual_family"]),
                anomaly=group.get("anomaly", {}),
                source=spec.measurement_source,
            )
            trace.append(
                {
                    "control_step": step + 1,
                    "phase": phase,
                    "phase_one_complete": phase_one_complete,
                    "measurement_source": spec.measurement_source,
                    "metric_weights": list(metric_weights),
                    "active_dofs": list(active_dofs),
                    "positions_before_mm": position_dict(before),
                    "positions_after_mm": position_dict(next_position),
                    "measured_metrics_before": metrics_dict(measured),
                    "clean_metrics_before": metrics_dict(clean),
                    "selected_action": planned["selected_action"],
                    "selected_requested_action": planned["selected_requested_action"],
                    "planner": planned,
                    "clean_metrics_after": metrics_dict(next_clean),
                    "measured_metrics_after": metrics_dict(next_measured),
                    "clean_normalized_error_after": strict_components(
                        next_clean, target, reference
                    ).tolist(),
                    "observed_normalized_error_after": strict_components(
                        next_measured, target, reference
                    ).tolist(),
                    "measurement_evidence_before": measurement_evidence,
                    "measurement_evidence_after": next_measurement_evidence,
                    "simulator_valid": bool(next_capture["auxiliary"]["simulator_valid"]),
                    "simulator_clipping_fraction": float(
                        next_capture["auxiliary"]["clipping_fraction"]
                    ),
                }
            )
            position = next_position
            capture = next_capture
            clean = next_clean
            measured = next_measured
            sensor_image = next_sensor_image
            measurement_evidence = next_measurement_evidence
            if not bool(capture["auxiliary"]["simulator_valid"]):
                termination_reason = "simulator_invalid"
                break
        clean_components = strict_components(clean, target, reference)
        observed_components = strict_components(measured, target, reference)
        return {
            "group_id": str(group["group_id"]),
            "base_state_id": str(group["base_state_id"]),
            "split": str(group["split"]),
            "visual_family": str(group["visual_family"]),
            "intervention_type": str(group["intervention_type"]),
            "plan_name": plan_name,
            "plan_spec": spec.to_dict(),
            "cem_seed": int(cem_seed),
            "fixed_controller_config": dict(self.fixed_config),
            "fixed_controller_config_hash": canonical_hash(self.fixed_config),
            "action_bounds": {
                "low": bounds.action_low.tolist(),
                "high": bounds.action_high.tolist(),
            },
            "strict_all_five_success": bool(
                float(clean_components.max())
                <= float(self.fixed_config["strict_success_threshold"])
            ),
            "terminal_normalized_error": float(clean_components.max()),
            "terminal_normalized_error_per_metric": clean_components.tolist(),
            "terminal_observed_normalized_error": float(observed_components.max()),
            "steps": len(trace),
            "boundary_risk_cost": boundary_risk_cost,
            "boundary_violation_count": violation_count,
            "termination_reason": termination_reason,
            "initial_clean_metrics": metrics_dict(initial_clean),
            "target_metrics": metrics_dict(target),
            "terminal_clean_metrics": metrics_dict(clean),
            "terminal_measured_metrics": metrics_dict(measured),
            "phase_transitions": phase_transitions,
            "initial_probe_audit": probe_audit,
            "safe_subset": list(safe_subset),
            "complete_actuator_actions": [row["selected_action"] for row in trace],
            "active_actuator_trajectory": [row["active_dofs"] for row in trace],
            "measurement_source_trajectory": [row["measurement_source"] for row in trace],
            "metric_weight_trajectory": [row["metric_weights"] for row in trace],
            "trace": trace,
            "final_sensor_image_peak": float(np.asarray(sensor_image).max()),
        }
